version: '3.7'
services:
  localstack:
    container_name: local-aws-services
    build:
      context: .
      dockerfile: ./Dockerfile.localstack
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,sqs,es
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - "HOSTNAME=${MY_DOCKER_IP:-127.0.0.1}"
      - "HOSTNAME_EXTERNAL=${MY_DOCKER_IP:-127.0.0.1}"
    volumes:
      - ./data/localstack:/tmp/localstack

  mysql:
    container_name: local-mysql-db
    build:
      context: .
      dockerfile: ./Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lambda_pass_root
      - MYSQL_USER=lambda_user
      - MYSQL_PASSWORD=lambda_pass
      - MYSQL_DATABASE=lambda_db